### ISSUE TITLE
Python requirement

### ISSUE THREAD

**Issue by CHENBIN99** [openxpu/pai#24]
Thanks for your great work to maintain the OpenPAI!

I am very happy to know that you have successfully supported OpenPAI on Ubuntu 18, 20 and 22, but I have some problems installing OpenPAI on ubuntu 22.04, about python installation **ruamel.ymal**

The main error message is:
> ERROR: Could not build wheels for ruamel.yaml, which is required to install pyproject.toml-based projects

I noticed that your requirement file requires that ruamel.yaml needs to be kept at version **0.15.96**, but there is no existing whl file for python3.10 in this version, so the above error occurs when compiling

I have install the python-dev and other package follow this [guide](https://stackoverflow.com/questions/75736939/error-could-not-build-wheels-for-python-ldap-which-is-required-to-install-pypr), but this error still exists.

My error may not have much to do with OpenPAI, and it is still in the stage of building the dependent environment. 
I really want to ask how to solve this problem, thank you very much😭

**Comment by CHENBIN99** [comment]
Env:
System: Ubuntu 22.04 LTS
Python: 3.10.6

**Comment by Bob-xpucube** [comment]
Hi Bin
Thanks for using openxpu/pai. There may be a little misunderstanding here. XPU supports Ubuntu18/20/22, but OpenPAI can only support 18 now. The porting work is scheduled but not start right now.
If you have any time and interest, we are happy to see you can have try to support Ubuntu 20/22.
