### ISSUE TITLE
the url of k8s-ds-amdgpu-db.yaml is not found

### ISSUE THREAD

**Issue by jiaxiaolei** [openxpu/pai#25]
**Organization Name**:

**Short summary about the issue/question**:  the url of k8s-ds-amdgpu-db.yaml is not found

**Brief what process you are following**: 

https://github.com/openxpu/pai/blob/master/src/device-plugin/deploy/start.sh.template +42

svn cat https://github.com/RadeonOpenCompute/k8s-device-plugin.git/trunk/k8s-ds-amdgpu-dp.yaml \
    | kubectl apply --overwrite=true -f - || exit $?

the url https://github.com/RadeonOpenCompute/k8s-device-plugin.git/trunk/k8s-ds-amdgpu-dp.yaml can not work

**How to reproduce it**:

**OpenPAI Environment**:
- OpenPAI version:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by jiaxiaolei** [comment]
how to pull my modify to  openxpu/pai. 

I➜  openxpu_pai git:(dev-jia) git push origin dev-jia
ERROR: Permission to openxpu/pai.git denied to jiaxiaolei.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Ray-xpucube** [comment]
Thanks for your contribute to this project. And a pull request has been merged to the project.
